### PR TITLE
Add Canon EOS R7 and R10

### PR DESCRIPTION
**Pull request by cytrinox**
CRAW samples not available, so not enabled this time.

### CODE REVIEW

**Comment by cytrinox** [comment]
We need samples for these cameras.
RAW, CRAW, BURST

**Comment by lclevy** [comment]
Hi Daniel, yes the usual craw/heif/dpraw and burst/roll (yuv 10 bits?) are interesting

**Comment by coven** [comment]
I can provide any needed samples, what is needed?

**Comment by lclevy** [comment]
And dual pixel if R7 does it, please

**Comment by coven** [comment]
There's no ISO 50, so I'm preparing 100, 800, 32000. How to send the samples?

**Comment by cytrinox** [comment]
You can use WeTransfer.com or any other sharing platform.
-- 
Best regards / Mit freundlichen Grüßen
Daniel Vogelbacher

Am 24. Juni 2022 16:55:12 UTC schrieb coven ***@***.***>:

**Comment by coven** [comment]
OK, since there are no preferences, they are here:
http://temp.vmh.net/R7_raw_samples.zip

**Comment by lclevy** [comment]
Thank you a lot!!

**Comment by coven** [comment]
Is there anything more I can do to help? FWIW this should be pretty similar to 90D and M6 mk II, as expected. At least everything seems to work right when I used 90D-derived parameters in RawTherapee.

**Comment by lclevy** [comment]
> OK, since there are no preferences, they are here: http://temp.vmh.net/R7_raw_samples.zip

Thank you a lot

**Comment by cytrinox** [comment]
Continue in other PRs, closing this as R7 support is already implemented.

**Pull request closed without merging**
